---

name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          always-auth: false
          node-version: ${{ matrix.node-version }}

      - name: Run npm ci
        run: npm ci

      - name: Run Tests
        run: npm run test:unit
        env:
          CI: true
